export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";

export const GET_USER_REPOS_REQUEST = "GET_USER_REPOS_REQUEST";
export const GET_USER_REPOS_SUCCESS = "GET_USER_REPOS_SUCCESS";
export const GET_USER_REPOS_FAILURE = "GET_USER_REPOS_FAILURE";

export const GET_USER_FOLLOWERS_REQUEST = "GET_USER_FOLLOWERS_REQUEST";
export const GET_USER_FOLLOWERS_SUCCESS = "GET_USER_FOLLOWERS_SUCCESS";
export const GET_USER_FOLLOWERS_FAILURE = "GET_USER_FOLLOWERS_FAILURE";

export const GET_INDIVIDUAL_REPO_REQUEST = "GET_INDIVIDUAL_REPO_REQUEST";
export const GET_INDIVIDUAL_REPO_SUCCESS = "GET_INDIVIDUAL_REPO_SUCCESS";
export const GET_INDIVIDUAL_REPO_FAILURE = "GET_INDIVIDUAL_REPO_FAILURE";
